name: Weekly Semantic Report

on:
  schedule:
    # Runs at 9:00 AM UTC on Monday every week
    - cron: '0 9 * * 1'
  workflow_dispatch:
    # This line enables the manual "Run workflow" button in the GitHub UI

jobs:
  run_agent:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
   
    - name: Run Python script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        NCBI_EMAIL: ${{ secrets.NCBI_EMAIL }}
        PUBMED_TERM: ${{ secrets.PUBMED_TERM }}
        CLINICALTRIALS_INTERVENTION: ${{ secrets.CLINICALTRIALS_INTERVENTION }}
        CLINICALTRIALS_CONDITION: ${{ secrets.CLINICALTRIALS_CONDITION }}
        SEMANTIC_SEARCH_TERMS: ${{ secrets.SEMANTIC_SEARCH_TERMS }}
        MAX_RECORDS: 50
        DAYS_BACK: 7
        SEMANTIC_THRESHOLD: 0.5
      run: python neurocell_agent_semantic.py
      
    - name: Upload Report Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: neurocell-reports-${{ github.run_id }}
        path: |
          *.csv
          *.db
          neurocell_agent_semantic.log
